# site settings
title: My website
subtitle: Powered by GitHub Pages
email: wolfdude.jacob@gmail.com
description: My personal website hosted by GitHub Pages and built/moderated by me
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Jacob Ahmaogak
street_address: a place you can't go...
city: Fairbanks
state: AK
zip_code: 99709
country: United States of America
phone: (907) 799 9730

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/jahmaogak0
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter: https://twitter.com/omninjaneers
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
